# Generated by Django 5.1 on 2024-08-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productvariant_delete_productvariation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
    ]
